version: '3.6'
services:
  app:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo:4.1.1-xenial
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
